config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }

  has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params_info)
    if @restaurant.valid?
      @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def params_info
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(params_info)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.valid?
      @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end


  private
  def params_info
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Hello we have those restaurants</h1>

  <%= link_to "Add new restaurant", "/restaurants/new" %>
<ul class="list-group">
  <% @restaurants.each do |restaurant| %>
    <li class="list-group-item"> <%= link_to restaurant.name , restaurant_path(restaurant) %>
      <p><strong>
      <%= link_to restaurant.category, restaurant_path(restaurant) %>
      </strong><p>

      </p>
     </li>
  <%end  %>
</ul>

app/views/restaurants/new.html.erb
<%= form_for (@restaurant), :html => {:class => "form-horizontal center"} do |f| %>
<div class="form-group">
name : <%= f.text_field :name %>
</div>
<div class="form-group">
address :<%= f.text_field :address %>
</div>
<div class="form-group">
phone_number :<%= f.text_field :phone_number %>
</div>
category :<%= f.select :category, Restaurant::CATEGORIES %>
<div class="">
<%=  f.submit %>
</div>
<% end  %>

app/views/restaurants/show.html.erb
<h1>welcome to your restaurant </h1>
<p>name : <%= @restaurant.name %></p>
<p>address : <%= @restaurant.address %></p>
<p>category : <%= @restaurant.category %></p>
<ul>
<% @restaurant.reviews.each do |review| %>
<li><%= review.content %> : <%= review.rating %></li>
<%end  %>
</ul>



<p>
<%= link_to "all restaurants", "/restaurants" %>
</p>
<%= link_to "leave a review", new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>